# Generated by Django 2.1 on 2018-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=3)),
                ('original', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
